ARG PANDAS_IMAGE_TAG

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# BUILD ETL BASE PANDAS
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
FROM pennsieve/pandas:$PANDAS_IMAGE_TAG as base_processor_pandas

ARG APK_PACKAGES
ARG PIP_PACKAGES
ARG PANDAS_PIP_PACKAGES

RUN apk -v add --no-cache ${APK_PACKAGES} && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --upgrade --no-cache-dir ${PIP_PACKAGES} ${PANDAS_PIP_PACKAGES}

COPY base_processor /usr/local/lib/python2.7/site-packages/base_processor
COPY bashlog        /bin/bashlog

ENTRYPOINT [""]

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# BUILD ETL BASE PANDAS TEST
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
FROM pennsieve/pandas:$PANDAS_IMAGE_TAG as base_processor_pandas_test

ARG APK_PACKAGES
ARG APK_TEST_PACKAGES
ARG PIP_PACKAGES
ARG PIP_TEST_PACKAGES
ARG PANDAS_PIP_PACKAGES

RUN apk -v --update add --no-cache ${APK_PACKAGES} ${APK_TEST_PACKAGES} && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --upgrade --no-cache-dir ${PIP_PACKAGES} ${PIP_TEST_PACKAGES} \
    ${PANDAS_PIP_PACKAGES}

COPY base_processor /usr/local/lib/python2.7/site-packages/base_processor
COPY bashlog        /bin/bashlog

ENTRYPOINT [""]
